name: CI
on:
  schedule:
    - cron: "0 0 1 * *" # Run every month
  # This way, we can make sure code doesn't break via external dependencies
  push:
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        python-version:
          - "3.12"
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Install dependencies
        run: uv sync --all-groups
      - name: Run test suite
        run: uv run pytest
      - name: Upload to CodeCov
        uses: codecov/codecov-action@v4
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
      - name: Build project
        run: uv build
